"""Reject substituted schema outputs and incomplete generator evidence."""
# SPDX-License-Identifier: MIT
import sys
sys.dont_write_bytecode = True
import hashlib
import json
import os
from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch

sys.path.insert(0,str(Path(__file__).resolve().parents[1]/'scripts'))
from environment import environment
from xsdc import generated_files, verify_generation, write_generated


class XsdcEvidence(unittest.TestCase):
    def setUp(self):
        self.temp=tempfile.TemporaryDirectory();self.addCleanup(self.temp.cleanup)
        self.root=Path(self.temp.name);self.generated=self.root/'generated'
        self.generated.mkdir();(self.generated/'apex.cpp').write_bytes(b'original generated bytes\n')
        pin=dict(compiler_options=['-c','-t'],generated_files=generated_files(self.generated))
        self.pin=self.root/'pin.json';self.pin.write_text(json.dumps(pin),encoding='utf-8')
        self.record=dict(pin_sha256=hashlib.sha256(self.pin.read_bytes()).hexdigest(),
            compiler_options=pin['compiler_options'],generated_files=pin['generated_files'],
            deterministic_generation_verified=True,negative_controls={'malformed_schema':True,'unknown_root':True})
        self.save()
        patcher=patch('xsdc.PIN',self.pin);patcher.start();self.addCleanup(patcher.stop)

    def save(self):
        (self.root/'generation.json').write_text(json.dumps(self.record),encoding='utf-8')

    def test_verified_outputs_are_reusable(self):
        self.assertEqual(verify_generation(self.root),self.record)

    def test_changed_missing_and_extra_outputs_fail(self):
        p=self.generated/'apex.cpp';original=p.read_bytes()
        p.write_bytes(b'changed\n')
        with self.assertRaises(RuntimeError):verify_generation(self.root)
        p.unlink()
        with self.assertRaises(RuntimeError):verify_generation(self.root)
        p.write_bytes(original);(self.generated/'extra.cpp').write_bytes(b'extra')
        with self.assertRaises(RuntimeError):verify_generation(self.root)

    def test_forged_output_hashes_cannot_override_the_pin(self):
        (self.generated/'apex.cpp').write_bytes(b'changed\n')
        self.record['generated_files']=generated_files(self.generated);self.save()
        with self.assertRaises(RuntimeError):verify_generation(self.root)

    def test_wrong_pin_options_and_missing_controls_fail(self):
        original=self.record.copy()
        for key,value in [('pin_sha256','0'*64),('compiler_options',['-c']),
                          ('deterministic_generation_verified',False),('negative_controls',{})]:
            with self.subTest(key=key):
                self.record={**original,key:value};self.save()
                with self.assertRaises(RuntimeError):verify_generation(self.root)

    def test_generation_cannot_escape_output(self):
        output=self.root/'output';output.mkdir()
        for name in ['../outside.cpp','/outside.cpp','C:/outside.cpp','..\\outside.cpp']:
            with self.subTest(name=name):
                with self.assertRaises(RuntimeError):write_generated(output,name,b'changed')
        self.assertFalse((self.root/'outside.cpp').exists())
        write_generated(output,'include/parser.h',b'valid')
        self.assertEqual((output/'include/parser.h').read_bytes(),b'valid')

    def test_generation_rejects_directory_aliases(self):
        destination=self.root/'destination';destination.mkdir()
        alias=self.root/'alias'
        try:alias.symlink_to(destination,target_is_directory=True)
        except (OSError,NotImplementedError):self.skipTest('Directory symlinks unavailable')
        with self.assertRaises(RuntimeError):write_generated(self.root,'alias/parser.h',b'changed')
        with self.assertRaises(RuntimeError):generated_files(alias)
        self.assertFalse((destination/'parser.h').exists())


if __name__=='__main__':
    os.environ.update(environment());unittest.main()
