"""Compile pinned AOSP libbinder and its libutils support for Android ARM64.

Produces relocatable archives and an explicit unresolved-import inventory.
This build does not link a service, attach Binder to ART, or execute Android code.
"""
# SPDX-License-Identifier: MIT
import sys
sys.dont_write_bytecode = True
import argparse
from concurrent.futures import ThreadPoolExecutor
import hashlib
import json
import os
from pathlib import Path
import struct
import subprocess
import time
import zipfile

from binder_aidl import COMPILER_OPTIONS, generated_files
from art_native_tls import compile_adaptation
from bionic_adapt import inventory
from environment import ROOT, environment
from ndk import obtain as obtain_ndk
from sources import obtain, obtain_files

CATALOG = ROOT / 'third_party/binder/native-sources.json'
GRAPH = ROOT / 'third_party/binder/native-libraries.json'


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_json(path):
    return json.loads(path.read_text(encoding='utf-8'))


def verify_aidl(directory):
    record = read_json(directory / 'generation.json')
    tool = read_json(ROOT / 'third_party/binder/aidl-tools.json')
    source = read_json(ROOT / 'third_party/sources.json')['binder-aidl']
    profile = tool['profiles'].get(record.get('profile'))
    if profile is None:
        raise RuntimeError('AIDL input has no reviewed native compiler profile')
    executable = profile['directory'] + '/' + profile['executable']
    expected = dict(tool_commit=tool['commit'], compiler_source_commit=tool['compiler_source_commit'],
        compiler_options=list(COMPILER_OPTIONS),
        compiler_sha256=next(i['sha256'] for i in tool['files'] if i['path'] == executable),
        source_files={i['path']: i['sha256'] for i in source['files']},
        native_execution_verified=True, deterministic_generation_verified=True, malformed_inputs_rejected=2)
    for key, value in expected.items():
        if record.get(key) != value:
            raise RuntimeError('AIDL input does not match pinned generation: ' + key)
    if record.get('generated_files') != generated_files(directory / 'generated'):
        raise RuntimeError('AIDL generated bytes differ from the generation record')
    return record


def verify_object_architecture(path):
    with path.open('rb') as source:
        header = source.read(64)
    if (len(header) != 64 or header[:7] != b'\x7fELF\x02\x01\x01' or
            struct.unpack_from('<HHI', header, 16) != (1, 183, 1)):
        raise RuntimeError('Expected a little-endian ARM64 ELF relocatable object: ' + path.name)


def verify_object_code(path, disassembly):
    verify_object_architecture(path)
    data = path.read_bytes()
    offset = struct.unpack_from('<Q', data, 40)[0]
    stride, count = struct.unpack_from('<HH', data, 58)
    if offset < 64 or stride != 64 or not count or offset + stride * count > len(data):
        raise RuntimeError('Invalid Binder object section table: ' + path.name)
    executable_bytes = 0
    for index in range(count):
        _, kind, flags, _, start, size, _, _, _, _ = struct.unpack_from('<IIQQQQIIQQ', data, offset + index * stride)
        if flags & 4:  # SHF_EXECINSTR; all selected ARM64 code is fixed-width.
            if kind != 1 or size % 4 or start + size > len(data):
                raise RuntimeError('Invalid Binder executable section: ' + path.name)
            executable_bytes += size
    boundary = inventory(disassembly)
    if (boundary['instruction_count'] * 4 != executable_bytes or
            any(value for key, value in boundary.items() if key != 'instruction_count')):
        raise RuntimeError('Binder object violates the native instruction boundary: ' + path.name)
    # file.cpp is empty when libbase is enabled. Accept zero instructions only
    # when the ELF executable sections also contain zero bytes.
    return dict(executable_bytes=executable_bytes, **boundary)


def symbol_inventory(text):
    defined, required, optional = set(), set(), set()
    for line in text.splitlines():
        parts = line.split()
        if len(parts) < 2 or len(parts[1]) != 1:
            continue  # llvm-nm archive member headings
        name, kind = parts[:2]
        if kind == 'U': required.add(name)
        elif kind in ('w', 'v'): optional.add(name)
        elif kind.isupper(): defined.add(name)
    return dict(defined=sorted(defined), required_external=sorted(required - defined),
                optional_external=sorted(optional - defined))


def run(command, log):
    result = subprocess.run(list(map(str, command)), capture_output=True)
    log.write_bytes(result.stdout + result.stderr)
    if result.returncode:
        raise RuntimeError('Binder build command failed; see ' + str(log))
    return result.stdout.decode('utf-8')


def ndk_notices(ndk, toolchain):
    if digest(toolchain / 'NOTICE') != read_json(ROOT / 'third_party/bionic/builtins.json')['notice_sha256']:
        raise RuntimeError('NDK toolchain license differs from the reviewed pin')
    return {'NDK-NOTICE.txt': ndk / 'NOTICE', 'NDK-TOOLCHAIN-NOTICE.txt': toolchain / 'NOTICE'}


def bundle_sources(output, catalog, sources, aidl, notices, extra_project=(), extra_files=()):
    files = {}
    for name, spec in catalog.items():
        for item in spec['files']:
            path = sources[name] / item['path']
            if digest(path) != item['sha256']:
                raise RuntimeError('Source changed during Binder build: ' + item['path'])
            files['upstream/' + name + '/' + item['path']] = path
    files['aidl/generation.json'] = aidl / 'generation.json'
    for name in generated_files(aidl / 'generated'):
        files['aidl/generated/' + name] = aidl / 'generated' / name
    for name, path in notices.items(): files['notices/' + name] = path
    project = ['LICENSE', 'THIRD_PARTY.md', 'docs/binder-build.md', 'scripts/build_binder.py',
               'scripts/binder_aidl.py', 'scripts/bionic_adapt.py', 'scripts/art_native_tls.py', 'scripts/tls_adapt.py',
               'scripts/sources.py', 'scripts/environment.py', 'scripts/ndk.py',
               'tests/test_binder_build.py', 'tests/test_art_native_tls.py', 'tests/test_tls_adapt.py',
               'third_party/binder/native-sources.json',
               'third_party/binder/native-libraries.json', 'third_party/binder/aidl-tools.json',
               'third_party/bionic/builtins.json', 'third_party/sources.json']
    project.extend(extra_project)
    if len(set(project)) != len(project):
        raise RuntimeError('Duplicate project source in Binder bundle')
    for name in project: files['artbox/' + name] = ROOT / name
    for name, path in extra_files:
        if name in files or not name.startswith('generated/') or '..' in Path(name).parts:
            raise RuntimeError('Invalid extra source bundle member')
        files[name] = path
    archive = output / 'corresponding-source.zip'
    with zipfile.ZipFile(archive, 'w', compression=zipfile.ZIP_DEFLATED) as target:
        for name, path in sorted(files.items()):
            entry = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            entry.compress_type = zipfile.ZIP_DEFLATED
            entry.external_attr = 0o100644 << 16
            target.writestr(entry, path.read_bytes())
    return dict(source_bundle_sha256=digest(archive), project_files={n:digest(ROOT / n) for n in project},
                source_notices={n:dict(path=s['notice'], sha256=s['notice_sha256']) for n,s in catalog.items()},
                ndk_notice_hashes={name:digest(path) for name,path in notices.items()})


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--aidl-dir', type=Path, required=True, help='Verified binder_aidl.py output from Mac or Linux')
    parser.add_argument('--ndk-root', type=Path)
    parser.add_argument('--build-dir', type=Path)
    parser.add_argument('--jobs', type=int, default=2)
    args = parser.parse_args()
    if args.jobs < 1: parser.error('--jobs must be positive')
    os.environ.update(environment())
    aidl = args.aidl_dir.resolve()
    generation = verify_aidl(aidl)
    output = (args.build_dir or Path(os.environ['ARTBOX_BUILD_DIR']) / 'm4/binder-native').resolve()
    output.mkdir(parents=True, exist_ok=True)
    result_path = output / 'build.json'
    if result_path.exists(): result_path.unlink()
    catalog, graph = read_json(CATALOG), read_json(GRAPH)
    sources = {name:obtain_files(name, spec, Path(os.environ['ARTBOX_CACHE_DIR'])) for name,spec in catalog.items()}
    common = read_json(ROOT / 'third_party/sources.json')
    for name in ('libbase-dex', 'liblog-dex', 'binder-aidl'):
        catalog[name] = common[name]; sources[name] = obtain(name)
    ndk = obtain_ndk(args.ndk_root)
    host = {'win32':'windows-x86_64', 'darwin':'darwin-x86_64', 'linux':'linux-x86_64'}[sys.platform]
    tools = ndk / 'toolchains/llvm/prebuilt' / host / 'bin'
    notices = ndk_notices(ndk, tools.parent)
    suffix = '.exe' if sys.platform == 'win32' else ''
    cxx, ar, nm, objdump = [tools / (n + suffix) for n in ('clang++', 'llvm-ar', 'llvm-nm', 'llvm-objdump')]
    flags = ['--target=' + graph['target'], '-std=' + graph['cpp_standard'], '-O1', '-DNDEBUG', '-fPIC',
        '-fno-exceptions', '-fno-rtti', '-ffixed-x18', '-ffixed-x27', '-ffixed-x28',
        '-ffunction-sections', '-fdata-sections', '-march=armv8-a', '-mno-outline-atomics',
        '-ffile-prefix-map=' + str(ROOT) + '=.', '-fdebug-prefix-map=' + str(ROOT) + '=.',
        '-DANDROID_UTILS_CALLSTACK_ENABLED=0', '-DANDROID_UTILS_REF_BASE_DISABLE_IMPLICIT_CONSTRUCTION',
        '-DANDROID_BASE_UNIQUE_FD_DISABLE_IMPLICIT_CONVERSION', '-DBINDER_WITH_KERNEL_IPC',
        '-Wall', '-Wextra', '-Werror', '-Wno-unused-parameter', '-Wno-missing-field-initializers',
        '-Wno-c99-designator', '-Wno-error=unused-but-set-variable']
    includes = [sources[name] / path for name,paths in graph['includes'].items() for path in paths]
    includes.append(aidl / 'generated/include')
    include_flags = [v for path in includes for v in ('-I', str(path))]
    jobs = []
    for library, spec in graph['libraries'].items():
        units = [(name, sources[spec['source']] / name) for name in spec['units']]
        if spec.get('generated_aidl'):
            units += [(name, aidl / 'generated' / name) for name in generation['generated_files'] if name.endswith('.cpp')]
        for name, path in units:
            obj = output / 'objects' / library / (name.replace('/', '__') + '.o')
            obj.parent.mkdir(parents=True, exist_ok=True)
            jobs.append((library, name, path, obj))
    started = time.monotonic()
    def compile_unit(job):
        library, name, source, obj = job
        unit_flags = graph['libraries'][library].get('unit_flags', {}).get(name, [])
        command = [cxx, *flags, *unit_flags, *include_flags, '-c', source, '-o', obj]
        run(command, obj.with_suffix('.log'))
        rule = graph['libraries'][library].get('compiler_tls', {}).get(name)
        tls = None
        if rule is not None:
            tls = compile_adaptation(list(map(str, command)), source, obj, output / 'compiler-tls',
                                     name.replace('/', '__'), rule)
        boundary = verify_object_code(obj, run([objdump, '-d', '--disassemble-zeroes', '--no-show-raw-insn', obj],
                                               obj.with_suffix('.asm')))
        print(library + ': ' + name, flush=True)
        return obj.relative_to(output).as_posix(), digest(obj), boundary, tls
    with ThreadPoolExecutor(max_workers=args.jobs) as pool:
        compiled = list(pool.map(compile_unit, jobs))
    objects = {name:sha for name,sha,_,_ in compiled}
    boundaries = {name:boundary for name,_,boundary,_ in compiled}
    compiler_tls = {name:tls for name,_,_,tls in compiled if tls is not None}
    archives = {}
    for library in graph['libraries']:
        path = output / (library + '.a')
        # Creating afresh excludes members removed by a later source selection.
        if path.exists(): path.unlink()
        members = [obj for lib,_,_,obj in jobs if lib == library]
        run([ar, 'rcsD', path, *members], output / (library + '-archive.log'))
        listing = run([ar, 't', path], output / (library + '-members.log')).splitlines()
        if listing != [obj.name for obj in members]:
            raise RuntimeError('Binder archive member inventory differs from compiled inputs')
        archives[path.name] = digest(path)
    symbols = symbol_inventory(run([nm, '--format=posix', '--extern-only', *[output / n for n in archives]], output / 'symbols.log'))
    (output / 'symbols.json').write_text(json.dumps(symbols, indent=2) + '\n', encoding='utf-8')
    record = dict(target=graph['target'], compiled_units=len(objects), objects=objects, archives=archives,
        instruction_boundaries=boundaries,
        compiler_tls=compiler_tls,
        compile_seconds=time.monotonic() - started, generation_sha256=digest(aidl / 'generation.json'),
        generated_files=generation['generated_files'], required_external_symbols=len(symbols['required_external']),
        symbols_sha256=digest(output / 'symbols.json'), compiler_version=run([cxx, '--version'], output / 'compiler.log').strip(),
        flags=[f.replace(str(ROOT), '${ARTBOX_ROOT}') for f in flags],
        unit_flags={name: spec.get('unit_flags', {}) for name, spec in graph['libraries'].items()},
        project_commit=subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=ROOT, text=True).strip(),
        link_verified=False, servicemanager_execution_verified=False, device_execution_verified=False,
        **bundle_sources(output, catalog, sources, aidl, notices))
    result_path.write_text(json.dumps(record, indent=2) + '\n', encoding='utf-8')
    print(json.dumps(dict(compiled_units=len(objects), required_external_symbols=record['required_external_symbols'], link_verified=False)))


if __name__ == '__main__':
    main()
