"""Pin the three integer runtime members and generate a Python divmod oracle."""
import hashlib
import json
import os
import subprocess
from environment import ROOT
from ndk import REVISION
from icu_guest_link import check_code


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def prepare(toolchain, output):
    output.mkdir(parents=True, exist_ok=True)
    pin = json.loads((ROOT / 'third_party/art/libcore-builtins.json').read_text(encoding='utf-8'))
    if pin['ndk_revision'] != REVISION or set(pin['members']) != {'udivti3.c.o', 'umodti3.c.o', 'udivmodti4.c.o'}:
        raise RuntimeError('Unreviewed libcore compiler runtime selection')
    tool = lambda name: toolchain / 'bin' / (name + ('.exe' if os.name == 'nt' else ''))
    commands = []

    def run(name, *args):
        command = list(map(str, [tool(name), *args]))
        commands.append(command)
        return subprocess.check_output(command)

    notice = toolchain / pin['notice']
    if digest(notice) != pin['notice_sha256']:
        raise RuntimeError('Compiler runtime notice changed')
    (output / 'COMPILER-RT-NOTICE.txt').write_bytes(notice.read_bytes())
    members = []
    for name, expected in pin['members'].items():
        path = output / name
        path.write_bytes(run('llvm-ar', 'p', toolchain / pin['archive'], name))
        if digest(path) != expected:
            raise RuntimeError('Compiler runtime member changed: ' + name)
        check_code(run('llvm-objdump', '-d', '--no-show-raw-insn', path).decode())
        members.append(path)
    # Rebuild a narrow archive; unrelated NDK members can never enter the link.
    archive = output / 'libartbox_uint128.a'
    if archive.exists(): archive.unlink()
    run('llvm-ar', 'rcs', archive, *members)
    mask = (1 << 128) - 1
    dividends = [0, 1, 2, (1 << 32)-1, (1 << 64)-1, 1 << 64, (1 << 64)+1,
                 (1 << 127)-1, 1 << 127, mask]
    divisors = [1, 2, 3, (1 << 32)-1, (1 << 32)+1, (1 << 64)-1, 1 << 64,
                (1 << 64)+1, 1 << 127, mask]
    pairs = [(n, d) for n in dividends for d in divisors]
    state = 0x123456789abcdef0123456789abcdef
    for i in range(128):
        state = (state * 6364136223846793005 + 1442695040888963407) & mask
        n = state
        state = (state * 6364136223846793005 + 1442695040888963407) & mask
        pairs.append((n, (state >> (i % 96)) or 1))
    rows, vectors = [], []
    for n, d in pairs:
        q, r = divmod(n, d)
        vectors.append(dict(zip(('n', 'd', 'q', 'r'), map(str, (n, d, q, r)))))
        words = [word for value in (n, d, q, r) for word in (value >> 64, value & ((1 << 64)-1))]
        rows.append('    {' + ', '.join('UINT64_C(0x%016x)' % word for word in words) + '},')
    header = output / 'vectors.h'
    header.write_text('/* Generated by ARTBox using Python integer divmod. MIT. */\n'
                      'static const uint64_t cases[][8] = {\n' + '\n'.join(rows) + '\n};\n', encoding='utf-8', newline='\n')
    (output / 'vectors.json').write_text(json.dumps(vectors, indent=2) + '\n', encoding='utf-8')
    source = ROOT / 'fixtures/libcore-integer128/check.c'
    caller = output / 'check.o'
    run('clang', '--target=aarch64-linux-android35', '-std=c11', '-O2', '-fPIC',
        '-ffreestanding', '-fno-builtin', '-fno-stack-protector', '-mbranch-protection=none',
        '-ffixed-x18', '-ffixed-x27', '-ffixed-x28', '-Wall', '-Wextra', '-Werror',
        '-I', output, '-c', source, '-o', caller)
    closed = output / 'check-closed.o'
    run('ld.lld', '-r', caller, *members, '-o', closed)
    if run('llvm-nm', '--undefined-only', closed).strip():
        raise RuntimeError('Integer oracle must not depend on host arithmetic')
    boundary = check_code(run('llvm-objdump', '-d', '--no-show-raw-insn', closed).decode())
    report = {'pin': pin, 'cases': len(vectors), 'source_sha256': digest(source),
              'header_sha256': digest(header), 'object_sha256': digest(caller),
              'archive_sha256': digest(archive), 'closed_sha256': digest(closed),
              'boundary': boundary, 'commands': commands}
    (output / 'build.json').write_text(json.dumps(report, indent=2) + '\n', encoding='utf-8')
    return report
