"""Build original AOSP XSdc and generate the pinned APEX XML parser."""
# SPDX-License-Identifier: MIT
import sys
sys.dont_write_bytecode = True
import argparse
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import subprocess
import tempfile
import zipfile
from environment import ROOT, environment
from jdk import obtain as obtain_jdk
from sources import obtain_files

PIN = ROOT / 'third_party/binder/xsdc.json'


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read(path):
    return json.loads(path.read_text(encoding='utf-8'))


def generated_files(directory):
    directory = Path(directory)
    if directory.is_symlink() or not directory.is_dir():
        raise RuntimeError('Generated directory must be a real directory')
    result = {}
    for path in sorted(directory.rglob('*')):
        if path.is_symlink():
            raise RuntimeError('Generated files must not be aliases')
        if path.is_file():
            result[path.relative_to(directory).as_posix()] = digest(path)
    return result


def write_generated(output, name, data):
    """Keep generated writes within the selected output, including parent aliases."""
    relative = PurePosixPath(name)
    if relative.is_absolute() or '..' in relative.parts or ':' in name or '\\' in name:
        raise RuntimeError('Invalid generated destination')
    output = Path(output).resolve()
    path = output
    for part in relative.parts:
        path = path / part
        if path.is_symlink() or not path.resolve().is_relative_to(output):
            raise RuntimeError('Generated destination must not be an alias')
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def verify_generation(directory):
    directory = Path(directory)
    pin, record = read(PIN), read(directory / 'generation.json')
    expected = dict(pin_sha256=digest(PIN), compiler_options=pin['compiler_options'],
        generated_files=pin['generated_files'], deterministic_generation_verified=True,
        negative_controls=dict(malformed_schema=True, unknown_root=True))
    if any(record.get(key) != value for key, value in expected.items()):
        raise RuntimeError('XSdc evidence differs from the pinned compiler/schema contract')
    if generated_files(directory / 'generated') != pin['generated_files']:
        raise RuntimeError('XSdc generated bytes differ from the reviewed output')
    return record


def prepare(output, java_home=None):
    os.environ.update(environment())
    output = Path(output).resolve(); output.mkdir(parents=True, exist_ok=True)
    result_path = output / 'generation.json'
    if result_path.exists(): result_path.unlink()
    pin = read(PIN)
    cache = Path(os.environ['ARTBOX_CACHE_DIR'])
    sources = {name: obtain_files('binder-' + name, spec, cache)
               for name, spec in pin['sources'].items()}
    java_home = Path(java_home).resolve() if java_home else obtain_jdk()[0]
    suffix = '.exe' if os.name == 'nt' else ''
    java, javac = [java_home / 'bin' / (name + suffix) for name in ('java', 'javac')]
    commons = cache / 'downloads/binder-xsdc'
    commons.mkdir(parents=True, exist_ok=True)
    notices = {}
    for name, spec in pin['commons_cli'].items():
        path = commons / name
        if path.is_symlink(): raise RuntimeError('Commons CLI cache must not be an alias')
        if not path.is_file():
            process = subprocess.run(['gh', 'api', spec['url'], '-H', 'Authorization:'],
                                     capture_output=True, timeout=120)
            process.check_returncode()
            if len(process.stdout) != spec['bytes'] or hashlib.sha256(process.stdout).hexdigest() != spec['sha256']:
                raise RuntimeError('Commons CLI download differs from the reviewed pin')
            path.write_bytes(process.stdout)
        if path.stat().st_size != spec['bytes'] or digest(path) != spec['sha256']:
            raise RuntimeError('Commons CLI archive differs from the reviewed pin')
        with zipfile.ZipFile(path) as archive:
            if archive.testzip() is not None: raise RuntimeError('Invalid Commons CLI archive')
            for notice, expected in pin['commons_cli_notices'].items():
                data = archive.read('META-INF/' + notice)
                if hashlib.sha256(data).hexdigest() != expected:
                    raise RuntimeError('Commons CLI notice changed')
                notices[notice] = data
    cli = commons / 'commons-cli-1.2.jar'
    java_files = [sources['xsdc'] / row['path'] for row in pin['sources']['xsdc']['files']
                  if row['path'].startswith('src/main/java/') and row['path'].endswith('.java')]
    if len(java_files) != 39: raise RuntimeError('XSdc Java source selection changed')
    commands = []

    def run(words, label, negative=False):
        command = list(map(str, words)); commands.append(command)
        process = subprocess.run(command, capture_output=True, timeout=120)
        (output / (label + '.stdout')).write_bytes(process.stdout)
        (output / (label + '.stderr')).write_bytes(process.stderr)
        if (process.returncode == 0) == negative:
            raise RuntimeError('XSdc command or its negative control failed: ' + label)
        return process

    version = run([javac, '-version'], 'javac-version')
    compiler_version = (version.stdout + version.stderr).decode('utf-8').strip()
    schema = sources['apex-schema'] / 'apexd/ApexInfoList.xsd'
    # A fresh class directory prevents a removed source from surviving as a class.
    with tempfile.TemporaryDirectory(dir=output, prefix='compiler-') as scratch:
        scratch = Path(scratch)
        classes = scratch / 'classes'; classes.mkdir()
        args = scratch / 'sources.txt'
        args.write_text('\n'.join('"' + p.as_posix().replace('"', '\\"') + '"' for p in java_files) + '\n', encoding='utf-8')
        run([javac, '-J-Xmx256m', '-J-Djava.io.tmpdir=' + os.environ['TMPDIR'],
             '-encoding', 'UTF-8', '--release', '17', '-cp', cli, '-d', classes, '@' + str(args)], 'compile')
        command = [java, '-Xmx128m', '-Djava.io.tmpdir=' + os.environ['TMPDIR'], '-Dfile.encoding=UTF-8',
                   '-cp', str(classes) + os.pathsep + str(cli), 'com.android.xsdc.Main']
        raw_hashes = {}
        for attempt in range(2):
            raw = scratch / ('raw-' + str(attempt)); raw.mkdir()
            run([*command, *pin['compiler_options'], '-o', raw, schema], 'generate-' + str(attempt))
            if set(generated_files(raw)) != set(pin['generated_files']):
                raise RuntimeError('XSdc output file inventory changed')
            for name, expected in pin['generated_files'].items():
                data = (raw / name).read_bytes()
                normalized = data.replace(b'\r\n', b'\n')
                if b'\r' in normalized or hashlib.sha256(normalized).hexdigest() != expected:
                    raise RuntimeError('XSdc generated source differs from reviewed bytes: ' + name)
                if attempt == 0:
                    raw_hashes[name] = hashlib.sha256(data).hexdigest()
                    for directory, contents in [('raw-generated', data), ('generated', normalized)]:
                        write_generated(output, directory + '/' + name, contents)
                elif raw_hashes[name] != hashlib.sha256(data).hexdigest():
                    raise RuntimeError('XSdc generation is not repeatable')
        malformed = scratch / 'malformed.xsd'; malformed.write_text('<broken', encoding='utf-8')
        controls = scratch / 'controls'; controls.mkdir()
        broken = run([*command, *pin['compiler_options'], '-o', controls, malformed], 'malformed-schema', True)
        if b'SAXParseException' not in broken.stderr:
            raise RuntimeError('Malformed schema failed for an unrelated reason')
        invalid_options = [value if value != 'apex-info-list' else 'artbox-no-such-root'
                           for value in pin['compiler_options']]
        absent = run([*command, *invalid_options, '-o', controls, schema], 'unknown-root', True)
        if b'Invalid root element' not in absent.stderr or generated_files(controls):
            raise RuntimeError('Invalid root control did not reject generation')

    project = ['LICENSE', 'THIRD_PARTY.md', 'scripts/xsdc.py', 'scripts/sources.py',
               'scripts/environment.py', 'scripts/jdk.py', 'tests/test_xsdc.py',
               'third_party/binder/xsdc.json', 'third_party/jdk.json']
    files = {'artbox/' + name: (ROOT / name).read_bytes() for name in project}
    for name, spec in pin['sources'].items():
        for row in spec['files']:
            path = sources[name] / row['path']
            if digest(path) != row['sha256']: raise RuntimeError('XSdc source changed during compilation')
            files['upstream/' + name + '/' + row['path']] = path.read_bytes()
    for name in pin['commons_cli']: files['commons-cli/' + name] = (commons / name).read_bytes()
    for name, data in notices.items(): files['notices/COMMONS-CLI-' + name] = data
    for name in pin['generated_files']:
        files['generated/' + name] = (output / 'generated' / name).read_bytes()
    bundle = output / 'corresponding-source.zip'
    with zipfile.ZipFile(bundle, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
        for name, data in sorted(files.items()):
            entry = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            entry.compress_type = zipfile.ZIP_DEFLATED; entry.external_attr = 0o100644 << 16
            archive.writestr(entry, data)
    canonical = lambda s: s.replace(str(java_home), '${JAVA_HOME}').replace(str(ROOT), '${ARTBOX_ROOT}')
    record = dict(pin_sha256=digest(PIN), compiler_options=pin['compiler_options'],
        generated_files=generated_files(output / 'generated'), raw_generated_files=raw_hashes,
        deterministic_generation_verified=True, negative_controls=dict(malformed_schema=True, unknown_root=True),
        source_bundle_sha256=digest(bundle), project_files={name:digest(ROOT / name) for name in project},
        java_units=len(java_files), compiler_version=compiler_version,
        commands=[[canonical(word) for word in command] for command in commands],
        project_commit=subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=ROOT, text=True).strip(),
        scope='Original AOSP XSdc and APEX schema; LF-normalized output, no guest or device execution')
    result_path.write_text(json.dumps(record, indent=2) + '\n', encoding='utf-8')
    verify_generation(output)
    return record


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--java-home', type=Path, help='Existing JDK 17+; otherwise use the pinned portable JDK')
    parser.add_argument('--build-dir', type=Path)
    args = parser.parse_args()
    os.environ.update(environment())
    output = args.build_dir or Path(os.environ['ARTBOX_BUILD_DIR']) / 'm4/xsdc'
    result = prepare(output, args.java_home)
    print('Original XSdc: 39 Java units, four reproducible generated files, both rejection controls pass')
    return result


if __name__ == '__main__': main()
